// Familiar unified theme — runtime resolver (server side).
//
// Single source of truth is ./defaults.json. This module:
//   1. loads those defaults,
//   2. overlays FAMILIAR_THEME_* env vars (the flattened [theme] TOML section —
//      the generic familiar.toml loader is a SEPARATE agent; we only CONSUME
//      the env contract here),
//   3. validates every color, failing clearly,
//   4. derives consumer artifacts: the browser CSS variables and a restty
//      GhosttyTheme object (semantic colors + ANSI 16 palette).
//
// The env contract (parallel to scripts/familiar-theme.sh so bash + node agree):
//   role   background        -> FAMILIAR_THEME_BACKGROUND
//   role   selectionBg       -> FAMILIAR_THEME_SELECTION_BG   (camel -> SNAKE)
//   ansi   brightBlack       -> FAMILIAR_THEME_ANSI_BRIGHT_BLACK
// Nested TOML [theme.ansi].bright_black already arrives as
// FAMILIAR_THEME_ANSI_BRIGHT_BLACK, so the mapping is a straight camel->SNAKE.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const DEFAULTS_PATH = path.join(HERE, "defaults.json");

export type ThemeRoles = {
  background: string;
  surface: string;
  surfaceDim: string;
  overlay: string;
  text: string;
  muted: string;
  accent: string;
  success: string;
  warning: string;
  error: string;
  border: string;
  borderMuted: string;
  selectionBg: string;
  cursor: string;
  cursorText: string;
};

export type AnsiPalette = {
  black: string; red: string; green: string; yellow: string;
  blue: string; magenta: string; cyan: string; white: string;
  brightBlack: string; brightRed: string; brightGreen: string; brightYellow: string;
  brightBlue: string; brightMagenta: string; brightCyan: string; brightWhite: string;
};

export type Theme = { name: string; roles: ThemeRoles; ansi: AnsiPalette };

type RawTheme = { name: string; roles: Record<string, string>; ansi: Record<string, string> };

/** #rgb / #rrggbb / #rrggbbaa. We normalise to lowercase #rrggbb(aa). */
const HEX = /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/;

export class ThemeError extends Error {}

function validateHex(role: string, value: unknown): string {
  if (typeof value !== "string" || !HEX.test(value.trim())) {
    throw new ThemeError(
      `theme: role "${role}" has invalid color ${JSON.stringify(value)} — expected #rgb, #rrggbb, or #rrggbbaa`,
    );
  }
  let v = value.trim().toLowerCase();
  if (v.length === 4) v = "#" + v[1] + v[1] + v[2] + v[2] + v[3] + v[3];
  return v;
}

/** camelCase role -> FAMILIAR_THEME_SNAKE_UPPER (roles) or _ANSI_ prefixed. */
function envKey(name: string, ansi: boolean): string {
  const snake = name.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();
  return ansi ? `FAMILIAR_THEME_ANSI_${snake}` : `FAMILIAR_THEME_${snake}`;
}

function loadDefaults(): RawTheme {
  return JSON.parse(fs.readFileSync(DEFAULTS_PATH, "utf8")) as RawTheme;
}

/**
 * Resolve the effective theme: defaults overlaid by FAMILIAR_THEME_* env,
 * then fully validated. Throws ThemeError on any bad color.
 */
export function resolveTheme(env: NodeJS.ProcessEnv = process.env): Theme {
  const base = loadDefaults();
  const nameOverride = env.FAMILIAR_THEME_NAME;

  const roles = {} as ThemeRoles;
  for (const key of Object.keys(base.roles)) {
    const raw = env[envKey(key, false)] ?? base.roles[key];
    (roles as Record<string, string>)[key] = validateHex(key, raw);
  }

  const ansi = {} as AnsiPalette;
  for (const key of Object.keys(base.ansi)) {
    const raw = env[envKey(key, true)] ?? base.ansi[key];
    (ansi as Record<string, string>)[key] = validateHex(`ansi.${key}`, raw);
  }

  return { name: nameOverride?.trim() || base.name, roles, ansi };
}

const ANSI_ORDER: (keyof AnsiPalette)[] = [
  "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",
  "brightBlack", "brightRed", "brightGreen", "brightYellow",
  "brightBlue", "brightMagenta", "brightCyan", "brightWhite",
];

/** Ordered ANSI 0..15 hex list (index = SGR color number). */
export function ansiList(theme: Theme): string[] {
  return ANSI_ORDER.map((k) => theme.ansi[k]);
}

// --- consumer artifact: browser CSS ---------------------------------------
// Emitted at /theme.css. terminal.html/style.css read var(--fm-*). Kept in
// sync with the legacy names style.css already used so nothing else changes.
export function toCss(theme: Theme): string {
  const r = theme.roles;
  const a = theme.ansi;
  const lines: string[] = [
    `/* generated by familiar theme resolver — do not edit; source services/gateway/src/theme/defaults.json */`,
    `:root {`,
    `  --fm-background: ${r.background};`,
    `  --fm-surface: ${r.surface};`,
    `  --fm-surface-dim: ${r.surfaceDim};`,
    `  --fm-overlay: ${r.overlay};`,
    `  --fm-text: ${r.text};`,
    `  --fm-muted: ${r.muted};`,
    `  --fm-accent: ${r.accent};`,
    `  --fm-success: ${r.success};`,
    `  --fm-warning: ${r.warning};`,
    `  --fm-error: ${r.error};`,
    `  --fm-border: ${r.border};`,
    `  --fm-border-muted: ${r.borderMuted};`,
    `  --fm-selection-bg: ${r.selectionBg};`,
    `  --fm-cursor: ${r.cursor};`,
    `  --fm-cursor-text: ${r.cursorText};`,
    // Back-compat aliases: the existing style.css / offline.html vars.
    `  --term-bg: ${r.background};`,
    `  --frame-fg: ${r.text};`,
    `  --accent: ${r.accent};`,
  ];
  ANSI_ORDER.forEach((k, i) => {
    const kebab = k.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
    lines.push(`  --fm-ansi-${i}: ${a[k]}; /* ${kebab} */`);
  });
  lines.push(`}`);
  return lines.join("\n") + "\n";
}

// --- consumer artifact: restty GhosttyTheme --------------------------------
// restty's Restty({ terminal: { theme } }) accepts a GhosttyTheme: semantic
// colors as {r,g,b} bytes plus a 256-entry palette (we fill 0..15). This
// REPLACES the hardcoded getBuiltinTheme("Catppuccin Mocha") in terminal.js so
// browser panes render the resolved theme (bg/fg/cursor/selection/ANSI16).
function hexToRgb(hex: string): { r: number; g: number; b: number; a?: number } {
  const h = hex.slice(1);
  const r = parseInt(h.slice(0, 2), 16);
  const g = parseInt(h.slice(2, 4), 16);
  const b = parseInt(h.slice(4, 6), 16);
  const out: { r: number; g: number; b: number; a?: number } = { r, g, b };
  if (h.length === 8) out.a = parseInt(h.slice(6, 8), 16);
  return out;
}

export function toResttyTheme(theme: Theme): unknown {
  const palette: ({ r: number; g: number; b: number } | undefined)[] = new Array(256).fill(undefined);
  ansiList(theme).forEach((hex, i) => { palette[i] = hexToRgb(hex); });
  return {
    name: theme.name,
    colors: {
      background: hexToRgb(theme.roles.background),
      foreground: hexToRgb(theme.roles.text),
      cursor: hexToRgb(theme.roles.cursor),
      cursorText: hexToRgb(theme.roles.cursorText),
      selectionBackground: hexToRgb(theme.roles.selectionBg),
      selectionForeground: hexToRgb(theme.roles.text),
      palette,
    },
    raw: {},
  };
}
